index:
  path: /
  controller: ZoiloMora\FactuSOL\Entrypoint\Web\DefaultController::index

agents.get_all:
  path: /agents
  controller: \ZoiloMora\FactuSOL\Entrypoint\Web\Agent\GetAllAgents
  methods: [GET]

agents.get_by_id:
  path: /agents/{agentId}
  controller: \ZoiloMora\FactuSOL\Entrypoint\Web\Agent\GetByIdAgent
  methods: [GET]
