index:
  path: /
  controller: ZoiloMora\FactuSOL\Entrypoint\Web\DefaultController::index

agents.get_all:
  path: /agents
  controller: \ZoiloMora\FactuSOL\Entrypoint\Web\Agent\GetAllAgents
  methods: [GET]

agents.get_by_id:
  path: /agents/{agentId}
  controller: \ZoiloMora\FactuSOL\Entrypoint\Web\Agent\GetByIdAgent
  methods: [GET]

taxes.get_all:
  path: /taxes
  controller: \ZoiloMora\FactuSOL\Entrypoint\Web\Tax\GetAllTaxes
  methods: [GET]

taxes.get_by_id:
  path: /taxes/{taxId}
  controller: \ZoiloMora\FactuSOL\Entrypoint\Web\Tax\GetByIdTax
  methods: [GET]

customers.get_all:
  path: /customers
  controller: \ZoiloMora\FactuSOL\Entrypoint\Web\Customer\GetAllCustomers
  methods: [GET]

customers.get_by_id:
  path: /customers/{customerId}
  controller: \ZoiloMora\FactuSOL\Entrypoint\Web\Customer\GetByIdCustomer
  methods: [GET]

families.get_all:
  path: /families
  controller: \ZoiloMora\FactuSOL\Entrypoint\Web\Family\GetAllFamilies
  methods: [GET]

families.get_by_id:
  path: /families/{familyId}
  controller: \ZoiloMora\FactuSOL\Entrypoint\Web\Family\GetByIdFamily
  methods: [GET]
